### ISSUE TITLE
[BUG] this.parent.viewContainer is not a function

### ISSUE THREAD

**Issue by mluis** [formio/angular-material-formio#8]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Local deployment
    - Version: "angular-material-formio": "^1.0.2"
- Frontend framework: Angular 8
- Browser: Chrome
- Browser version: Version 77.0.3865.120 (Official Build) (64-bit)

## Steps to Reproduce
1. Use the json form sample in this issue.
2. <mat-formio [form]="form" (submit)="onSubmit($event)"></mat-formio>
3. Error will be on the development console of the browser.

## Example

```js
{
        "components": [
            {
                "title": "Page 1",
                "label": "Page 1",
                "type": "panel",
                "key": "page1",
                "input": false,
                "components": [
                    {
                        "label": "Number",
                        "mask": false,
                        "type": "number",
                        "input": true,
                        "key": "number2"
                    },
                    {
                        "input": true,
                        "key": "textArea",
                        "label": "Text Area",
                        "type": "textarea"
                    }
                ]
            }
        ],
        "display": "wizard"
    }
```

**Comment by JoeyHengst** [comment]
@travist can you look at this one asap plz. This is also a blocker for use since all our forms will display as a wizard. Thank you! We are using the latest dependencies.
```
"angular-formio": "^4.3.0-beta.2",
"formiojs": "^4.5.0" 
```

**Comment by efortes** [comment]
Hallo 
@travist I have this issue also when rendering a wizard. 
At the moment this issue is blocking our project from continue. Do you know how to solve this issue?

**Comment by Yobikap** [comment]
Hi @travist we have the same problem. This should be fixed as asap, or else we can not continue.
Thanks.

**Comment by travist** [comment]
This library still does not support wizards. The customer who funded it did not have an immediate need for wizards, which is why it wasn't implemented. It absolutely is on our list to implement this, but is currently below other critical items. If someone has an immediate need for this, and does not want to contribute to the Open Source project with their own implementation, then it is an option to pay Form.io to expedite this implementation. Email our support at form.io if you would like to go down that road. If not then it may take a couple of weeks for this to work its way up our priority list.

**Comment by wag110894** [comment]
support@form.io

**Comment by efortes** [comment]
@travist @wag110894 we will discuss with the team. Thank you for the answer.

**Comment by adornala** [comment]
@travist How long do you think this is gonna take, if we make it to top of your priority list? (To make wizard compatible)

**Comment by travist** [comment]
Just FYI to everyone.. we did get a sponsorship for this feature and I have been allocated to work on it this week. Should be done by the end of the week!

**Comment by travist** [comment]
This is now done and is in the latest 1.4.0 release!

**Comment by efortes** [comment]
Thank you for the update. We will test this ASAP.

**Comment by yannickcare** [comment]
Still occurring in 1.8.0 on angular 8.2.14
